### ISSUE TITLE
Determine Hardware Details For Lift Device

### ISSUE THREAD

**Issue by skallaher** [KentridgeRobotics/2020Robot#10]
Determine the following, consulting with the relevant IPT Team if necessary:

- [ ] How many motors/actuators will be necessary?
- [ ] Of those motors/actuators how many will have and/or need encoders on them?
- [ ] What information about the device will need to be gathered using sensors?
- [ ] What sensors will be used?

**Comment by cpdupuis** [comment]
Another question:

- [ ] Will we need pneumatics?
