### ISSUE TITLE
Autonomous command: back up

### ISSUE THREAD

**Issue by cpdupuis** [KentridgeRobotics/2020Robot#107]
We can get points in autonomous period for moving our robot off the starting line.

Let's start by making an autonomous command that backs up a bit. It should do something like this:

Constant:
- maxDriveTimeMilliseconds

Member variables:
- startTimeMilliseconds
- isDone

Initialize:
- store the current time in startTimeMilliseconds
- set isDone to false
-  set throttle for DriveSubsystem to -0.4 (both right and left).

Execute:
- get the current time again
- if current time is greater than startTimeMilliseconds plus maxDriveTimeMilliseconds, set isDone to true

IsFinished:
Return isDone

End:
Set throttle to zero

**Comment by n7jti** [comment]
Tony has started work on this
