### ISSUE TITLE
Control Panel requirements

### ISSUE THREAD

**Issue by tpunn** [KentridgeRobotics/2020Robot#11]
**Hardware**: some mechanism to spin the wheel (motor), a color sensor and encoder
**Software**: PID controller to move motors, AdaFruit sensor connect to Arduino -> RoboRio, and Encoder to read sensor data

useful information about PIDs for us freshmen beginners:
https://frc-pdr.readthedocs.io/en/latest/control/pid_control.html

**Comment by tpunn** [comment]
We need a gyro sensor to measure rotations of the wheel too.

**Comment by skallaher** [comment]
I would suggest an encoder for this purpose. Given the diameters of the Control Panel and the wheel spinning, you should be able to determine how much you've turned the Control Panel based upon how much the smaller wheel has been spun. Though this would be dependent on the design of the Control Panel manipulator. A discussion with the IPT might be warranted here.
