### ISSUE TITLE
Chassis requirements 

### ISSUE THREAD

**Issue by ghost** [KentridgeRobotics/2020Robot#12]
We need to have sensors that use odometry to sense the position of the robot. Chassis team currently does not know what kind of sensors they are planning to use and thus, our main code will have to be able to cover every kind of sensor....basically.

**Comment by YummyKimchi** [comment]
like.....buy it? Im pretty sure you and i are just supposed to be programming the basic functions of the chassis which is actually still being built

**Comment by tpunn** [comment]
yaried means you need to write a class for reading the sensor

**Comment by YummyKimchi** [comment]
how? i didnt learn this.....

**Comment by ghost** [comment]
We need 4 sensors for the chassis. 2 on each side of the chassis. The chassis group has not decided which kind of sensors they want to use yet.

**Comment by YummyKimchi** [comment]
> We need to have sensors that use odometry to sense the position of the robot.

**Comment by YummyKimchi** [comment]
> > We need to have sensors that use odometry to sense the position of the robot.

**Comment by YummyKimchi** [comment]
//collects data from an analog sensor

int sensorpin = 0;                 // analog pin used to connect the sharp sensor
int val = 0;                 // variable to store the values from sensor(initially zero)

void setup()
{
  Serial.begin(9600);               // starts the serial monitor
}
 
void loop()
{
  val = analogRead(sensorpin);       // reads the value of the sharp sensor
  Serial.println(val);            // prints the value of the sensor to the serial monitor
  delay(400);                    // wait for this much time before printing next value
}

**Comment by YummyKimchi** [comment]
Code for infrared sensor:

int sensorpin = 0;                 // analog pin used to connect the sharp sensor
int val = 0;                 // variable to store the values from sensor(initially zero)

void setup()
{
  Serial.begin(9600);               // starts the serial monitor
}
 
void loop()
{
  val = analogRead(sensorpin);       // reads the value of the sharp sensor
  Serial.println(val);            // prints the value of the sensor to the serial monitor
  delay(400);                    // wait for this much time before printing next value
}
