### ISSUE TITLE
Double solenoids

### ISSUE THREAD

**Issue by chanjcl** [KentridgeRobotics/2020Robot#18]
Kaitlin handed programming team a double solenoid and asked us to look into how to utilize it for pneumatics.  There is documentation in WPILIB on how to set the values and program it.  I've asked Luke to look into it.  I heard last Luke has reassigned this task to someone else? (Tony)  Programming is keeping the solenoids at the moment.

**Comment by YummyKimchi** [comment]
We will be working on this today as we could not do so on Saturday as were busy helping out with working out different sensors.
