### ISSUE TITLE
Limelight camera

### ISSUE THREAD

**Issue by tpunn** [KentridgeRobotics/2020Robot#19]
## Limelight Camera Programming

- [x] Get camera to work
- [x] Send xy position and area to RoboRio
- [ ] Create math methods to use data
- [ ] Control robot with this information

https://docs.limelightvision.io/en/latest/networktables_api.html

**Basic code to get information from the LimeLight**
```
NetworkTable table = NetworkTableInstance.getDefault().getTable("limelight");
NetworkTableEntry tx = table.getEntry("tx");
NetworkTableEntry ty = table.getEntry("ty");
NetworkTableEntry ta = table.getEntry("ta");
double x = tx.getDouble(0.0);
double y = ty.getDouble(0.0);
double area = ta.getDouble(0.0);
```

**Comment by YummyKimchi** [comment]
Ta:
 Percentage of the target compared to the screen being projected from the camera.
Tl:
The gist is, how fast the pictures/video feed being sent from the camera is being taken in terms of milliseconds.

**Comment by ghost** [comment]
Tx: Horizontal offset from the cross hair based on the target.
Ty: Vertical offset from the cross hair based on the target.

**Comment by ghost** [comment]
tshort: Side length of shortest side(of the fitted bounding box?).
tlong: Side length of longest side(of the fitted bounding box?).

**Comment by tpunn** [comment]
I think the bounding box is the perimeter it puts around the target.

**Comment by ghost** [comment]
tv: Whether the limelight has any valid targets. It will be a 0 or 1.

**Comment by ghost** [comment]
ts: Skew/rotation (-90 degrees to 0 degrees)

**Comment by ghost** [comment]
thor: Horizontal side length of the rough bounding box
tvert: Vertical side length of the rough bounding box
(Both range from 0 to 320 pixels)

**Comment by ghost** [comment]
tan(a1+a2) = (h2-h1) / d

d = (h2-h1) / tan(a1+a2)

h(1) = height of camera above the floor h(2) = The height of the target
a(1) = mounting angle a(2) = Angle to the target.
d = distance 
![DistanceEstimation](https://user-images.githubusercontent.com/56093052/73505403-470e8000-4387-11ea-8fd1-bc509fe88b3b.jpg)

**Comment by ghost** [comment]
https://docs.wpilib.org/en/latest/docs/software/vision-processing/introduction/cameraserver-class.html
I think this will help with the camera server.

**Comment by vkang2004** [comment]
addAxisCamera()= appears in the Dashboard’s drop down list of cameras
startAutomaticCapture()=starts a server for it so it can be viewed from the dashboard.
getVideo()=allows you to get images from the camera for image processing on the roboRIO 
putVideo()= put the video image as any size or quality it is
