### ISSUE TITLE
Adafruit Color Sensor requirements

### ISSUE THREAD

**Issue by tpunn** [KentridgeRobotics/2020Robot#6]
### Getting color on spinner

documentation--https://learn.adafruit.com/adafruit-color-sensors/arduino-code

goals--Use this to send RGB color to the Arduino, then send it off to RoboRio. After this, we need to start working on Java handling of the color and response on the motor.

repo--https://github.com/tpunn/arduino-adafruit

**Comment by vkang2004** [comment]
And also encode it

**Comment by tpunn** [comment]
Encoding will be separate, this is just the adafruit sensor if we use it

**Comment by vkang2004** [comment]
we are thinking of using Color Sensor V3

**Comment by vkang2004** [comment]
also NEO 550 Brushless Motor

**Comment by YummyKimchi** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. *beep

**Comment by vkang2004** [comment]
link for coding Sensor color https://ftc-tricks.com/overview-color-sensor/

**Comment by tpunn** [comment]
Working version. If at a certain condition, it can read and match the color to the right one consistently.
https://github.com/tpunn/arduino-adafruit/blob/master/identifyRGB.ino

**Comment by vkang2004** [comment]
code for master reader
// Wire Master Reader
// by Nicholas Zambetti <http://www.zambetti.com>

// Demonstrates use of the Wire library
// Reads data from an I2C/TWI slave device
// Refer to the "Wire Slave Sender" example for use with this

// Created 29 March 2006

// This example code is in the public domain.


#include <Wire.h>

void setup()
{
  Wire.begin(0x29);        // join i2c bus (address optional for master)
  Serial.begin(9600);  // start Serial for output
}

void loop()
{
  Wire.requestFrom(2, 6);    // request 6 bytes from slave device #2

  while(Wire.available())    // slave may send less than requested
  { 
    char c = Wire.read(); // receive a byte as character
    Serial.print(c);         // print the character
  }

  delay(500);
}

**Comment by vkang2004** [comment]
// Wire Slave Receiver
// by Nicholas Zambetti <http://www.zambetti.com>

// Demonstrates use of the Wire library
// Receives data as an I2C/TWI slave device
// Refer to the "Wire Master Writer" example for use with this

// Created 29 March 2006

// This example code is in the public domain.


#include <Wire.h>

void setup()
{
  Wire.begin(4);                // join i2c bus with address #4
  Wire.onReceive(receiveEvent); // register event
  Serial.begin(9600);           // start serial for output
}

void loop()
{
  delay(100);
}

// function that executes whenever data is received from master
// this function is registered as an event, see setup()
void receiveEvent(int howMany)
{
  while(1 < Wire.available()) // loop through all but the last
  {
    char c = Wire.read(); // receive byte as a character
    Serial.print(c);         // print the character
  }
  int x = Wire.read();    // receive byte as an integer
  Serial.println(x);         // print the integer
}

**Comment by vkang2004** [comment]
#include <Wire.h>
#include <Wire.h>
#include "Adafruit_TCS34725.h"
Adafruit_TCS34725 tcs = Adafruit_TCS34725(TCS34725_INTEGRATIONTIME_700MS, TCS34725_GAIN_1X);

double newDistance = 0;

float colors[][4] = {
  {161.3868, 56.9116, 56.2178},
  {48.6522, 125.8932, 83.3956},
  {28.623, 99.7964, 127.0984},
  {96.3246, 107.721, 51.8917}
};


float colorDistance(float red1, float green1, float blue1, float red2, float green2, float blue2) {
  //return ((red2-red1)*(red2-red1))  +  ((green2-green1) *(green2-green1)) +((blue2-blue1)*(blue2-blue1))+((clear2-clear1)*(clear2-clear1));
  uint64_t sum_of_squares; 
  sum_of_squares = sqrt(pow(red2-red1,2)+pow(green2-green1,2)+pow(blue2-blue1,2));
  //Serial.println(sum_of_squares);
return ( sum_of_squares  );
};
void setup() {
    Serial.begin(9600);

  if(tcs.begin()){
    //
  }else{
    Serial.println("No TCS34725");
    while(1);
  }
}

void loop() {
  float r,g,b;
  tcs.setInterrupt(false);
  delay(60);
  tcs.getRGB(&r,&g,&b);
  tcs.setInterrupt(true);
  
  //uint16_t r, g, b, c, colorTemp, lux;
  //tcs.getRawData(&r, &g, &b, &c);
  Serial.print("R:");
  Serial.print(r);
  Serial.print(" G:");
  Serial.print(g);
  Serial.print(" B:");
  Serial.println(b);
 
  //colorTemp = tcs.calculateColorTemperature_dn40(r, g, b, c);
  //lux = tcs.calculateLux(r, g, b);
}
int color = 0;

  double prev_dist = -1.0;
for( byte i = 0; i < 4; i++ ) {
   double distance = colorDistance(r,g,b,colors[i][0],colors[i][1],colors[i][2]);
   if (i == 0 || distance < prev_dist)
   {
      color = i;
      prev_dist = distance;
      newDistance = distance;
   }

  }

void requestEvent() {
   

  if (color == 0) Serial.print("R ");
  else if (color == 1) Serial.print("G ");
  else if (color == 2) Serial.print("B ");
  else if (color == 3) Serial.print("Y ");
  else Serial.print("N ");
  Serial.print(" Distance:");
  Serial.println(newDistance);
}
