### ISSUE TITLE
Create a Drive subsystem

### ISSUE THREAD

**Issue by cpdupuis** [KentridgeRobotics/2020Robot#7]
The drive subsystem controls the motors used for driving the robot.

Our robot will be using Rev Robotics Spark Max motor controllers: http://www.revrobotics.com/rev-11-2158/

The class for interfacing with these motor controllers is here: http://www.revrobotics.com/content/sw/max/sw-docs/java/com/revrobotics/CANSparkMax.html

**Comment by nhl01** [comment]
Drive subsystem created on 1/25/2020. Still need to add brakes and boost mode.
